### ISSUE TITLE
Opportunity to optimise Rope performance

### ISSUE THREAD

**Issue by hummy123** [backtracking/ocaml-bazaar#1]
Hi there.

This is a cool collection of data structures. I published a modified version of a Piece Tree structure (which is is similar to a Rope; both edit text) to opam and was asked about comparing the performance between your library and mine. 

They are pretty competitive so far (you can see my benchmark comparison on real world editing traces [here](https://discuss.ocaml.org/t/ann-release-of-piece-rope-0-9-0/11734?u=hummy123)), but I think yours has the opportunity to become faster than it already is.

[This](https://github.com/hummy123/ocaml-piecerope/blob/546ee35d847092cde7b31074da3c754d61db6238/bench/bench.ml#L31) is the code I had to use when I wanted to delete a length of characters from your library, and that's obviously less efficient than it could be because you have to index to the specified place in the Rope every time. I think your library can outright become faster than mine if that were reimplemented. 

It's likely not a huge issue though because users most likely won't notice a difference that small, but I'm letting you know in case you think it's worth it.

All the best,
Humza

**Comment by backtracking** [comment]
Hi,
And thanks for the nice words :-)
Indeed, you're right, it is not very efficient to delete characters one at a time with `delete`.
But I would expect something like
```
let remove r ofs len =
  append (sub r 0 ofs) (sub r (ofs + len) (length r - ofs - len))
```
to be not that bad.

**Comment by backtracking** [comment]
Anyway, thanks for the suggestion. I think I'll add the `remove` function (with the implementation above) to my library.
